services:
  hydra-transportes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hydra-transportes-web
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - NODE_ENV=production
